version: "3.8"

services:
  postgres:
    image: postgres:latest
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: "psql postgresql://root:password@localhost:5432/batman?sslmode=disable"
      interval: 10s
      timeout: 5s
      retries: 5

  minio:
    image: quay.io/minio/minio
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - minio_data:/data

  app:
    build:
      dockerfile: Dockerfile
      context: ./
    env_file:
      - .env
    ports:
      - "1234:1234"
    depends_on:
      postgres:
        condition: service_healthy
    links:
      - postgres
volumes:
  postgres_data:
  minio_data:
  app_data:
