// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.590
package view

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func Player(songsrc string) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"flex items-center justify-between bg-gray-800 text-white px-4 py-2\"><div class=\"flex items-center space-x-2\"><button hx-get=\"/api/play\" hx-target=\"#player\" hx-swap=\"innerHTML\"><!-- Play button SVG --></button><div class=\"truncate\"><span id=\"song-title\">Song Title</span> - <span id=\"artist\">Artist Name</span></div></div><div class=\"w-full\"><div class=\"h-2 bg-gradient-to-r from-green-500 to-green-700 rounded-full\"><template hx-swap hx-boost=\"true\"><div id=\"progress-bar\" class=\"h-full bg-white rounded-full animate-fill-up\" style=\"width: 0%;\"></div></template></div></div><button hx-get=\"/api/next\" hx-target=\"#player\" hx-swap=\"innerHTML\"><!-- Next button SVG --></button></div><audio id=\"player\" src=\"{{songsrc}}\"></audio><!-- Ensuring songsrc is correctly interpolated -->")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}

// front
//<form action="http://your-restapi-server:8080/upload" method="POST" enctype="multipart/form-data">
//  <input type="file" name="file"> <button type="submit">Upload</button>
//</form>
